apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resecrets.juanjo.garciaamaya.com
spec:
  scope: Namespaced
  group: juanjo.garciaamaya.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: |
                Specification of the behavior of the ReSecret object
              type: object
              properties:
                name:
                  type: string
                  description: Name of the secret resource to be created
                secrets:
                  description: |
                    A list of secrets to include in the new secret by copying or directly defined.
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                        description: Each key must consist of alphanumeric characters, '-', '_' or '.'.
                      value:
                        type: string
                        description: |
                          The serialized form of the secret data is a base64 encoded string, representing
                          the arbitrary (possibly non-string) data value here. Described in
                          https://tools.ietf.org/html/rfc4648#section-4
                      secretKeyRef:
                        type: object
                        description: |
                          Selects a key of a secret in the pod's namespace

                          SecretKeySelector selects a key of a Secret.
                        properties:
                          name:
                            type: string
                            description: |
                              Name of the referent. More info:
                              https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                          key:
                            type: string
                            description: The key of the secret to select from. Must be a valid secret key.

  names:
    kind: ReSecret
    plural: resecrets
    singular: resecret
    shortNames:
      - rscr
