apiVersion: juanjo.garciaamaya.com/v1alpha1
kind: ReSecret
metadata:
  name: keycloak-pg-db
  labels:
    app: keycloak
spec:
  name: keycloak-db-secret-resecret
  secrets:
    - key: POSTGRES_DATABASE
      secretKeyRef:
        name: keycloak2-postgrescluster-pguser-keycloak
        key: dbname
    - key: POSTGRES_EXTERNAL_ADDRESS
      value: a2V5Y2xvYWsyLXBvc3RncmVzY2x1c3Rlci1oYS5hbHRrZXljbG9hay5zdmMuY2x1c3Rlci5sb2NhbA==
    - key: POSTGRES_EXTERNAL_PORT
      value: NTQzMg==
    - key: POSTGRES_PASSWORD
      secretKeyRef:
        name: keycloak2-postgrescluster-pguser-keycloak
        key: password
    - key: POSTGRES_USERNAME
      secretKeyRef:
        name: keycloak2-postgrescluster-pguser-keycloak
        key: user
    - key: SSLMODE
      value: cmVxdWlyZQ==
